### ISSUE TITLE
Laravel Nova pagination stops working after pressing back / foward once

### ISSUE THREAD

**Issue by preliot** [chris-ware/nova-breadcrumbs#22] opened 2019-05-24 10:30 UTC
Nova 2.0.5
Laravel 5.8.18
https://nova.laravel.com/docs/1.0/resources/#pagination (simple style)

Laravel Nova pagination will stop to work after pressing a back/forward button once. It will continue to show a disabled icon.

When i disable  this tool in my NovaServiceProvider, everything works.

Same issue as (but that one is closed) #16

**Comment by chris-ware** [comment] 2019-05-24 10:46
Duplicate of #14

**Closed by chris-ware** 2019-05-24 10:46 UTC
