### ISSUE TITLE
TypeError: "this.resourceInformation.perPageOptions is undefined"

### ISSUE THREAD

**Issue by Dontorpedo** [chris-ware/nova-breadcrumbs#53] opened 2019-10-14 20:54 UTC
After installation, this errors appears.. and the indexpage isn't loading..

i am on laravel 5.8 and nova 2.4

**Comment by bigperson** [comment] 2019-10-15 13:12
I have some problem

**Comment by chris-ware** [comment] 2019-10-15 16:26
It seems that something under the hood has changed with 2.4.0, that has affected how this package works. I'll investigate and attempt to resolve.

**Comment by bigperson** [comment] 2019-10-24 15:40
I reproduced the problem on version 2.5.0

**Comment by fnmancinelli** [comment] 2019-10-29 17:26
I've this error too.

**Comment by chris-ware** [comment] 2019-10-31 19:48
I've tested this and I'm unable to reproduce. Can you confirm that you've run `php artisan nova:publish` since updating? I'm running 1.2.9 and Nova 2.6.1

**Comment by fnmancinelli** [comment] 2019-11-11 16:03
We updated Nova to version 2.6.1 and after a new installation of this package, it worked correctly.
`php artisan nova:publish` was executed during the `composer require ...`

**Comment by chris-ware** [comment] 2019-11-15 15:00
`php artisan nova:publish` should be run on any update of Nova to re-publish its assets. Those assets have to match what the breadcrumbs assets suggest due to the way that this package works. I'm closing this issue for now as it seems to be solved by simple re-publishing, however if it re-appears, please re-open.

**Closed by chris-ware** 2019-11-15 15:00 UTC
Labels: bug, question
